<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Product\RegOS.Product.Application\RegOS.Product.Application.csproj" />
    <ProjectReference Include="..\..\Product\RegOS.Product.Infrastructure\RegOS.Product.Infrastructure.csproj" />
    <ProjectReference Include="..\..\RegulatoryApplication\RegOS.RegulatoryApplication.Application\RegOS.RegulatoryApplication.Application.csproj" />
    <ProjectReference Include="..\..\RegulatoryApplication\RegOS.RegulatoryApplication.Infrastructure\RegOS.RegulatoryApplication.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Organization\RegOS.Organization.Application\RegOS.Organization.Application.csproj" />
    <ProjectReference Include="..\..\Organization\RegOS.Organization.Infrastructure\RegOS.Organization.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Platform\RegOS.Platform.Application\RegOS.Platform.Application.csproj" />
    <ProjectReference Include="..\..\Platform\RegOS.Platform.Infrastructure\RegOS.Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\ReferenceData\RegOS.ReferenceData.Application\RegOS.ReferenceData.Application.csproj" />
    <ProjectReference Include="..\..\ReferenceData\RegOS.ReferenceData.Infrastructure\RegOS.ReferenceData.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Submission\RegOS.Submission.Application\RegOS.Submission.Application.csproj" />
    <ProjectReference Include="..\..\Submission\RegOS.Submission.Infrastructure\RegOS.Submission.Infrastructure.csproj" />
    <ProjectReference Include="..\..\ProductDocument\RegOS.ProductDocument.Application\RegOS.ProductDocument.Application.csproj" />
    <ProjectReference Include="..\..\ProductDocument\RegOS.ProductDocument.Infrastructure\RegOS.ProductDocument.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Registration\RegOS.Registration.Application\RegOS.Registration.Application.csproj" />
    <ProjectReference Include="..\..\Registration\RegOS.Registration.Infrastructure\RegOS.Registration.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Interaction\RegOS.Interaction.Application\RegOS.Interaction.Application.csproj" />
    <ProjectReference Include="..\..\Interaction\RegOS.Interaction.Infrastructure\RegOS.Interaction.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Study\RegOS.Study.Application\RegOS.Study.Application.csproj" />
    <ProjectReference Include="..\..\Study\RegOS.Study.Infrastructure\RegOS.Study.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Labeling\RegOS.Labeling.Application\RegOS.Labeling.Application.csproj" />
    <ProjectReference Include="..\..\Labeling\RegOS.Labeling.Infrastructure\RegOS.Labeling.Infrastructure.csproj" />
  </ItemGroup>

</Project>
