// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegOS.Persistence;

#nullable disable

namespace RegOS.Persistence.Migrations
{
    [DbContext(typeof(RegOSDbContext))]
    [Migration("20260802041450_AddSubmissionStatusHistory")]
    partial class AddSubmissionStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegOS.Interaction.Domain.Commitments.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegulatoryApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceCorrespondenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceInspectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceMeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("TenantId", "OwnerUserId");

                    b.HasIndex("TenantId", "CurrentStatus", "DueOn");

                    b.ToTable("Commitments", (string)null);
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Correspondence.HaCorrespondence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorityDivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CorrespondenceTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegulatoryApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ResponseDueOn")
                        .HasColumnType("date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityDivisionId");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("CorrespondenceTypeId");

                    b.HasIndex("RegulatoryApplicationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OccurredOn");

                    b.HasIndex("TenantId", "ResponseDueOn");

                    b.ToTable("HaCorrespondence", (string)null);
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Inspections.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrganizationSiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledFor")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("OrganizationSiteId");

                    b.HasIndex("TenantId", "CurrentStatus", "ScheduledFor");

                    b.ToTable("Inspections", (string)null);
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Meetings.HaMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorityDivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Minutes")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegulatoryApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledFor")
                        .HasColumnType("date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityDivisionId");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("TenantId", "CurrentStatus", "ScheduledFor");

                    b.ToTable("HaMeetings", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationSiteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("LastName");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationSiteId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.ContactEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactEmails", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.ContactPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactPhones", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.ContactRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ContactId", "RoleId")
                        .IsUnique();

                    b.ToTable("ContactRoleAssignments", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Organization.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NameNativeLanguage")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LegalName");

                    b.HasIndex("TenantId");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Organization.OrganizationIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SchemeId");

                    b.HasIndex("OrganizationId", "SchemeId")
                        .IsUnique();

                    b.ToTable("OrganizationIdentifiers", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationDivision.OrganizationDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TenantId");

                    b.ToTable("OrganizationDivisions", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationSite.OrganizationSite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NameNativeLanguage")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("OrganizationSites", (string)null);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationSite.SiteIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationSiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SchemeId");

                    b.HasIndex("OrganizationSiteId", "SchemeId")
                        .IsUnique();

                    b.ToTable("SiteIdentifiers", (string)null);
                });

            modelBuilder.Entity("RegOS.Persistence.ReadModels.ProductDirectoryRow", b =>
                {
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("Products", (string)null);
                });

            modelBuilder.Entity("RegOS.Persistence.ReadModels.UserDirectoryRow", b =>
                {
                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.ToTable((string)null);

                    b.ToView("Users", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.Invitation.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.PasswordReset.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.RefreshToken.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.Session.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.Tenant.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.UserCredential.UserCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.GlobalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.MarketStatusEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicinalProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicinalProductId");

                    b.HasIndex("MedicinalProductId", "OccurredOn");

                    b.ToTable("MarketStatusHistory", (string)null);
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.MedicinalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentMarketStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("StatusDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("CountryId", "CurrentMarketStatus");

                    b.HasIndex("GlobalProductId", "CountryId");

                    b.ToTable("MedicinalProducts", (string)null);
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.TradeName", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("MedicinalProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MedicinalProductId", "Language")
                        .IsUnique();

                    b.ToTable("TradeNames", (string)null);
                });

            modelBuilder.Entity("RegOS.ProductDocument.Domain.Aggregates.ProductDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("GlobalProductId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("GlobalProductId", "Name")
                        .IsUnique();

                    b.ToTable("ProductDocuments", (string)null);
                });

            modelBuilder.Entity("RegOS.ProductDocument.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductDocumentId");

                    b.HasIndex("ProductDocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("SubmissionTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("RegulatoryTemplates", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PublishedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegulatoryTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegulatoryTemplateId");

                    b.HasIndex("RegulatoryTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RegulatoryTemplateVersions", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RequiredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegulatoryTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RegulatoryTemplateVersionId");

                    b.HasIndex("SectionId", "DocumentTypeId")
                        .IsUnique();

                    b.ToTable("RequiredDocuments", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.TemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegulatoryTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("RegulatoryTemplateVersionId");

                    b.HasIndex("RegulatoryTemplateVersionId", "Code")
                        .IsUnique();

                    b.ToTable("TemplateSections", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.ValidationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RegulatoryTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegulatoryTemplateVersionId");

                    b.HasIndex("RegulatoryTemplateVersionId", "Code")
                        .IsUnique();

                    b.ToTable("ValidationRules", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.DocumentType.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"TenantId\" IS NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Geography.Country.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Organization.ContactRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("ContactRoles", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Organization.IdentifierScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("IdentifierSchemes", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Authorities", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Regulatory.Authority.AuthorityDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId", "TenantId", "Name")
                        .IsUnique();

                    b.ToTable("AuthorityDivisions", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Regulatory.Correspondence.CorrespondenceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CorrespondenceTypes", (string)null);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.SubmissionType.SubmissionType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubmissionTypes", (string)null);
                });

            modelBuilder.Entity("RegOS.Registration.Domain.Aggregates.Registration.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ApprovedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<Guid>("HolderOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicinalProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginatingApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("HolderOrganizationId");

                    b.HasIndex("OriginatingApplicationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("MedicinalProductId", "CurrentStatus");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("RegOS.Registration.Domain.Aggregates.Registration.RegistrationStatusEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("RegistrationId", "OccurredOn");

                    b.ToTable("RegistrationStatusHistory", (string)null);
                });

            modelBuilder.Entity("RegOS.RegulatoryApplication.Domain.Aggregates.RegulatoryApplication.RegulatoryApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantOrganizationId");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("GlobalProductId", "CountryId", "AuthorityId")
                        .IsUnique();

                    b.ToTable("RegulatoryApplications", (string)null);
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BoundTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("BoundTemplateVersionId");

                    b.HasIndex("SubmissionTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ApplicationId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"SequenceNumber\" IS NOT NULL");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.SubmissionDeletion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeletesSubmissionDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateSectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("SubmissionId", "ProductDocumentId", "TemplateSectionId")
                        .IsUnique();

                    b.ToTable("SubmissionDeletions", (string)null);
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.SubmissionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Operation")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacesSubmissionDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TemplateSectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("TemplateSectionId");

                    b.HasIndex("SubmissionId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("SubmissionId", "ProductDocumentId")
                        .IsUnique();

                    b.ToTable("SubmissionDocuments", (string)null);
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Commitments.Commitment", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RegOS.Interaction.Domain.Commitments.CommitmentStatusEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<Guid>("CommitmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateOnly>("OccurredOn")
                                .HasColumnType("date");

                            b1.Property<DateTime>("RecordedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CommitmentId");

                            b1.ToTable("CommitmentStatusEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CommitmentId");
                        });

                    b.Navigation("History");
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Correspondence.HaCorrespondence", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.AuthorityDivision", null)
                        .WithMany()
                        .HasForeignKey("AuthorityDivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Correspondence.CorrespondenceType", null)
                        .WithMany()
                        .HasForeignKey("CorrespondenceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RegOS.Interaction.Domain.Correspondence.CorrespondenceAttachment", "Attachments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<long>("FileSizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("HaCorrespondenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.Property<string>("StoragePath")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateTime>("UploadedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("HaCorrespondenceId");

                            b1.ToTable("CorrespondenceAttachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HaCorrespondenceId");
                        });

                    b.OwnsMany("RegOS.Interaction.Domain.Correspondence.HaQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<int>("CurrentStatus")
                                .HasColumnType("integer");

                            b1.Property<Guid>("HaCorrespondenceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid?>("OwnerUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ResponseText")
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)");

                            b1.Property<DateOnly?>("TargetResponseOn")
                                .HasColumnType("date");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.HasKey("Id");

                            b1.HasIndex("HaCorrespondenceId");

                            b1.HasIndex("CurrentStatus", "TargetResponseOn");

                            b1.ToTable("HaQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HaCorrespondenceId");

                            b1.OwnsMany("RegOS.Interaction.Domain.Correspondence.HaQuestionStatusEntry", "History", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("Id");

                                    b2.Property<Guid>("HaQuestionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Note")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<DateOnly>("OccurredOn")
                                        .HasColumnType("date");

                                    b2.Property<DateTime>("RecordedOnUtc")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<int>("Status")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("HaQuestionId");

                                    b2.ToTable("HaQuestionStatusEntries", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("HaQuestionId");
                                });

                            b1.Navigation("History");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Inspections.Inspection", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Organization.Domain.Aggregates.OrganizationSite.OrganizationSite", null)
                        .WithMany()
                        .HasForeignKey("OrganizationSiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("RegOS.Interaction.Domain.Inspections.InspectionStatusEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<Guid>("InspectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateOnly>("OccurredOn")
                                .HasColumnType("date");

                            b1.Property<DateTime>("RecordedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("InspectionId");

                            b1.ToTable("InspectionStatusEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InspectionId");
                        });

                    b.Navigation("History");
                });

            modelBuilder.Entity("RegOS.Interaction.Domain.Meetings.HaMeeting", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.AuthorityDivision", null)
                        .WithMany()
                        .HasForeignKey("AuthorityDivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RegOS.Interaction.Domain.Meetings.HaMeetingStatusEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<Guid>("HaMeetingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateOnly>("OccurredOn")
                                .HasColumnType("date");

                            b1.Property<DateTime>("RecordedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("HaMeetingId");

                            b1.ToTable("HaMeetingStatusEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HaMeetingId");
                        });

                    b.Navigation("History");
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.Contact", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Geography.Country.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegOS.Organization.Domain.Aggregates.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Organization.Domain.Aggregates.OrganizationSite.OrganizationSite", null)
                        .WithMany()
                        .HasForeignKey("OrganizationSiteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.ContactEmail", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Contact.Contact", null)
                        .WithMany("Emails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.ContactPhone", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Contact.Contact", null)
                        .WithMany("Phones")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.ContactRoleAssignment", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Contact.Contact", null)
                        .WithMany("Roles")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RegOS.ReferenceData.Domain.Organization.ContactRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Organization.OrganizationIdentifier", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Organization.Organization", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RegOS.ReferenceData.Domain.Organization.IdentifierScheme", null)
                        .WithMany()
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationDivision.OrganizationDivision", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationSite.OrganizationSite", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("RegOS.Organization.Domain.Aggregates.OrganizationSite.PostalAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationSiteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("City");

                            b1.Property<Guid>("CountryId")
                                .HasColumnType("uuid")
                                .HasColumnName("CountryId");

                            b1.Property<string>("Line1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AddressLine1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AddressLine2");

                            b1.Property<string>("Line3")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("AddressLine3");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("StateProvince")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("StateProvince");

                            b1.HasKey("OrganizationSiteId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("OrganizationSites");

                            b1.HasOne("RegOS.ReferenceData.Domain.Geography.Country.Country", null)
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("OrganizationSiteId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationSite.SiteIdentifier", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.OrganizationSite.OrganizationSite", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("OrganizationSiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RegOS.ReferenceData.Domain.Organization.IdentifierScheme", null)
                        .WithMany()
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.Invitation.Invitation", b =>
                {
                    b.HasOne("RegOS.Platform.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.PasswordReset.PasswordReset", b =>
                {
                    b.HasOne("RegOS.Platform.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.RefreshToken.RefreshToken", b =>
                {
                    b.HasOne("RegOS.Platform.Domain.Aggregates.Session.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegOS.Platform.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.Session.Session", b =>
                {
                    b.HasOne("RegOS.Platform.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Platform.Domain.Aggregates.UserCredential.UserCredential", b =>
                {
                    b.HasOne("RegOS.Platform.Domain.Aggregates.User.User", null)
                        .WithOne()
                        .HasForeignKey("RegOS.Platform.Domain.Aggregates.UserCredential.UserCredential", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.MarketStatusEntry", b =>
                {
                    b.HasOne("RegOS.Product.Domain.Product.MedicinalProduct", null)
                        .WithMany("MarketStatusHistory")
                        .HasForeignKey("MedicinalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.MedicinalProduct", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Geography.Country.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Product.Domain.Product.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.TradeName", b =>
                {
                    b.HasOne("RegOS.Product.Domain.Product.MedicinalProduct", null)
                        .WithMany("TradeNames")
                        .HasForeignKey("MedicinalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ProductDocument.Domain.Aggregates.ProductDocument", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.DocumentType.DocumentType", null)
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Product.Domain.Product.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ProductDocument.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("RegOS.ProductDocument.Domain.Aggregates.ProductDocument", null)
                        .WithMany("Versions")
                        .HasForeignKey("ProductDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplate", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.SubmissionType.SubmissionType", null)
                        .WithMany()
                        .HasForeignKey("SubmissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Platform.Domain.Aggregates.Tenant.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("RegulatoryTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RequiredDocument", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.DocumentType.DocumentType", null)
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", null)
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("RegulatoryTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.TemplateSection", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", null)
                        .WithMany("Sections")
                        .HasForeignKey("RegulatoryTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.ValidationRule", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", null)
                        .WithMany("ValidationRules")
                        .HasForeignKey("RegulatoryTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.DocumentType.DocumentType", b =>
                {
                    b.HasOne("RegOS.Platform.Domain.Aggregates.Tenant.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Geography.Country.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Regulatory.Authority.AuthorityDivision", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.SubmissionType.SubmissionType", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Registration.Domain.Aggregates.Registration.Registration", b =>
                {
                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Organization.Domain.Aggregates.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("HolderOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Product.Domain.Product.MedicinalProduct", null)
                        .WithMany()
                        .HasForeignKey("MedicinalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.RegulatoryApplication.Domain.Aggregates.RegulatoryApplication.RegulatoryApplication", null)
                        .WithMany()
                        .HasForeignKey("OriginatingApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RegOS.Registration.Domain.Aggregates.Registration.RegistrationStatusEntry", b =>
                {
                    b.HasOne("RegOS.Registration.Domain.Aggregates.Registration.Registration", null)
                        .WithMany("History")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.RegulatoryApplication.Domain.Aggregates.RegulatoryApplication.RegulatoryApplication", b =>
                {
                    b.HasOne("RegOS.Organization.Domain.Aggregates.Organization.Organization", null)
                        .WithMany()
                        .HasForeignKey("ApplicantOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.Regulatory.Authority.Authority", null)
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.Geography.Country.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Product.Domain.Product.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.Submission", b =>
                {
                    b.HasOne("RegOS.RegulatoryApplication.Domain.Aggregates.RegulatoryApplication.RegulatoryApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", null)
                        .WithMany()
                        .HasForeignKey("BoundTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RegOS.ReferenceData.Domain.SubmissionType.SubmissionType", null)
                        .WithMany()
                        .HasForeignKey("SubmissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("RegOS.Submission.Domain.Submission.SubmissionStatusEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("Id");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateOnly>("OccurredOn")
                                .HasColumnType("date");

                            b1.Property<DateTime>("RecordedOnUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SubmissionId");

                            b1.ToTable("SubmissionStatusEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("History");
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.SubmissionDeletion", b =>
                {
                    b.HasOne("RegOS.Submission.Domain.Submission.Submission", null)
                        .WithMany("Deletions")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.SubmissionDocument", b =>
                {
                    b.HasOne("RegOS.ProductDocument.Domain.Entities.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegOS.Submission.Domain.Submission.Submission", null)
                        .WithMany("Documents")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegOS.ReferenceData.Domain.Blueprint.TemplateSection", null)
                        .WithMany()
                        .HasForeignKey("TemplateSectionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Contact.Contact", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Phones");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.Organization.Organization", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("RegOS.Organization.Domain.Aggregates.OrganizationSite.OrganizationSite", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("RegOS.Product.Domain.Product.MedicinalProduct", b =>
                {
                    b.Navigation("MarketStatusHistory");

                    b.Navigation("TradeNames");
                });

            modelBuilder.Entity("RegOS.ProductDocument.Domain.Aggregates.ProductDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("RegOS.ReferenceData.Domain.Blueprint.RegulatoryTemplateVersion", b =>
                {
                    b.Navigation("RequiredDocuments");

                    b.Navigation("Sections");

                    b.Navigation("ValidationRules");
                });

            modelBuilder.Entity("RegOS.Registration.Domain.Aggregates.Registration.Registration", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("RegOS.Submission.Domain.Submission.Submission", b =>
                {
                    b.Navigation("Deletions");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
